# Generated by Django 5.1.4 on 2025-01-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
