# Generated by Django 5.1.4 on 2025-01-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
