# Generated by Django 5.1.5 on 2025-01-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0005_alter_comments_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images/'),
        ),
    ]
